/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts;

import com.sun.istack.internal.logging.Logger;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Smktelkom
 */
public class perpus extends javax.swing.JFrame {
    String nol_jam = "";
    String nol_menit = "";
    String nol_detik = "";

    /**
     * Creates new form perpus
     */
    public perpus() {
        initComponents();
        selectData();
        setTanggal();
        setJam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labeltanggal1 = new javax.swing.JLabel();
        labeljam = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        save = new javax.swing.JButton();
        del = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        print = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        judul = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        no = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        kembali = new com.toedter.calendar.JDateChooser();
        pinjam = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        denda = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        belum = new javax.swing.JRadioButton();
        sudah = new javax.swing.JRadioButton();
        jenis = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        data = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 72, 94));
        jPanel1.setLayout(null);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("\"Buku adalah Jendela Dunia\"");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 60, 200, 20);

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Perpustakaan Terpadu");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 10, 360, 40);

        labeltanggal1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labeltanggal1.setForeground(new java.awt.Color(255, 255, 255));
        labeltanggal1.setText("Tanggal");
        jPanel1.add(labeltanggal1);
        labeltanggal1.setBounds(730, 20, 100, 20);

        labeljam.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        labeljam.setForeground(new java.awt.Color(255, 255, 255));
        labeljam.setText("Jam");
        jPanel1.add(labeljam);
        labeljam.setBounds(730, 50, 100, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 90);

        jPanel3.setBackground(new java.awt.Color(83, 83, 83));

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        del.setText("Delete");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(del, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exit)
                .addGap(18, 18, 18)
                .addComponent(print)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(del)
                    .addComponent(clear)
                    .addComponent(refresh)
                    .addComponent(exit)
                    .addComponent(print))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(270, 100, 620, 50);

        jPanel2.setBackground(new java.awt.Color(83, 83, 83));
        jPanel2.setLayout(null);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(0, 40, 240, 20);

        jLabel3.setFont(new java.awt.Font("MingLiU_HKSCS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Alamat Peminjam");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 170, 160, 40);
        jPanel2.add(alamat);
        alamat.setBounds(10, 200, 170, 30);

        jLabel4.setFont(new java.awt.Font("MingLiU_HKSCS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Judul Buku");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 290, 100, 40);
        jPanel2.add(judul);
        judul.setBounds(10, 320, 170, 30);

        jLabel5.setFont(new java.awt.Font("MingLiU_HKSCS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("No Anggota");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 50, 120, 40);
        jPanel2.add(no);
        no.setBounds(10, 80, 170, 30);

        jLabel6.setFont(new java.awt.Font("MingLiU_HKSCS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nama Peminjam");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 110, 150, 40);
        jPanel2.add(nama);
        nama.setBounds(10, 140, 170, 30);

        jLabel9.setFont(new java.awt.Font("MingLiU_HKSCS", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tanggal Kembali");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 410, 160, 40);
        jPanel2.add(kembali);
        kembali.setBounds(10, 440, 170, 30);
        jPanel2.add(pinjam);
        pinjam.setBounds(10, 380, 170, 30);

        jLabel2.setFont(new java.awt.Font("MingLiU_HKSCS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ISIKAN DATA");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 10, 150, 30);

        jLabel1.setFont(new java.awt.Font("MingLiU_HKSCS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tanggal Pinjam");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 350, 160, 40);

        jLabel10.setFont(new java.awt.Font("MingLiU_HKSCS", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Jenis Buku");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 230, 100, 40);

        jLabel11.setFont(new java.awt.Font("MingLiU_HKSCS", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Status");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 530, 100, 40);
        jPanel2.add(denda);
        denda.setBounds(10, 500, 170, 30);

        jLabel12.setFont(new java.awt.Font("MingLiU_HKSCS", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Denda");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 470, 170, 40);

        buttonGroup1.add(belum);
        belum.setText("Belum Kembali");
        belum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                belumActionPerformed(evt);
            }
        });
        jPanel2.add(belum);
        belum.setBounds(93, 570, 110, 23);

        buttonGroup1.add(sudah);
        sudah.setText("Kembali");
        jPanel2.add(sudah);
        sudah.setBounds(10, 570, 70, 23);

        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Salah Satu--", "Pelajaran", "Novel", "Komik", " " }));
        jPanel2.add(jenis);
        jenis.setBounds(10, 260, 170, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 100, 240, 610);

        jPanel4.setBackground(new java.awt.Color(83, 83, 83));
        jPanel4.setLayout(null);

        data.setBackground(new java.awt.Color(0, 72, 94));
        data.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        data.setForeground(new java.awt.Color(255, 255, 255));
        data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NoAnggota", "NamaPeminjam", "AlamatPeminjam", "JenisBuku", "JudulBuku", "TanggalPinjam", "TanggalKembali", "Denda", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Long.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        data.setSelectionBackground(new java.awt.Color(0, 0, 0));
        data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(data);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(10, 11, 600, 520);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(270, 160, 620, 550);

        setSize(new java.awt.Dimension(917, 762));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-yy");
        String tanggalp = dateFormat.format(pinjam.getDate());
        String tanggalk = dateFormat.format(kembali.getDate());
        String ST = "";
        if (sudah.isSelected()) {
                    ST = "Kembali";
                } else {
                    ST = "Belum Kembali";
                }
        String JN = "";
        if (jenis.getSelectedItem().equals("Pelajaran")) {
                    JN = "Pelajaran";
                } else if(jenis.getSelectedItem().equals("Novel")){
                    JN = "Novel";
                } else if(jenis.getSelectedItem().equals("Komik")){
                    JN = "Komik";
                }
        if ("".equals(no.getText()) || "".equals(nama.getText()) || "".equals(alamat.getText()) || "".equals(JN)
                || "".equals(judul.getText()) || "".equals(tanggalp) || "".equals(tanggalk) || "".equals(denda.getText()) || "".equals(ST)){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            String SQL = "INSERT INTO t_siswa (NoAnggota,NamaPeminjam,AlamatPeminjam,JenisBuku,JudulBuku,TanggalPinjam,TanggalKembali,Denda,Status)"
            + "VALUES('"+no.getText()+"','"+nama.getText()+"','"+ alamat.getText()+"','"+JN+"','"+judul.getText()+"','"+tanggalp
            +"','"+tanggalk+"','"+denda.getText()+"','"+ST+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambah", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Sukses", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
        int baris = data.getSelectedRow();
        if (baris != -1) {
            String NoAnggota = data.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM t_siswa WHERE NoAnggota='"+NoAnggota+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_delActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        no.setText("");
        nama.setText("");
        alamat.setText("");
        jenis.setSelectedItem("");
        judul.setText("");
        ((JTextField)pinjam.getDateEditor().getUiComponent()).setText("");
        ((JTextField)kembali.getDateEditor().getUiComponent()).setText("");
        denda.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_clearActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataMouseClicked
        // TODO add your handling code here:
        int baris = data.getSelectedRow();
        if (baris != -1) {
            no.setText(data.getValueAt(baris, 0).toString());
            nama.setText(data.getValueAt(baris, 1).toString());
            alamat.setText(data.getValueAt(baris, 2).toString());
            if ("Pelajaran".equals(data.getValueAt(baris, 3).toString())) {
                jenis.setSelectedItem(true);
            } else if(jenis.getSelectedItem().equals("Novel")){
                jenis.setSelectedItem(true);
            } else if(jenis.getSelectedItem().equals("Komik")){
                jenis.setSelectedItem(true);
            }
            judul.setText(data.getValueAt(baris, 4).toString());
            ((JTextField)pinjam.getDateEditor().getUiComponent()).setText(data.getValueAt(baris, 5).toString());
            ((JTextField)kembali.getDateEditor().getUiComponent()).setText(data.getValueAt(baris, 6).toString());
            denda.setText(data.getValueAt(baris, 7).toString());
            if ("Kembali".equals(data.getValueAt(baris, 8).toString())) {
                sudah.setSelected(true);
            } else {
                belum.setSelected(true);
            }
        }
    }//GEN-LAST:event_dataMouseClicked

    private void belumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_belumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_belumActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Biodata Siswa SMK Telkom Malang");
        MessageFormat footer = new MessageFormat("Page (0,number,integer)    ");
        try {
            data.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_printActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_refreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(perpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(perpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(perpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(perpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new perpus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JRadioButton belum;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JTable data;
    private javax.swing.JButton del;
    private javax.swing.JTextField denda;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JTextField judul;
    private com.toedter.calendar.JDateChooser kembali;
    private javax.swing.JLabel labeljam;
    private javax.swing.JLabel labeltanggal1;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField no;
    private com.toedter.calendar.JDateChooser pinjam;
    private javax.swing.JButton print;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save;
    private javax.swing.JRadioButton sudah;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"NoAnggota","NamaPeminjam","AlamatPeminjam","JenisBuku","JudulBuku","TanggalPinjam","TanggalKembali","Denda","Status"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM t_siswa";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while(rs.next()) {
                String NoAnggota = rs.getString(1);
                String NamaPeminjam = rs.getString(2);
                String AlamatPeminjam = rs.getString(3);
                String JenisBuku = rs.getString(4);
                String JudulBuku = rs.getString(5);
                String TanggalPinjam = rs.getString(6);
                String TanggalKembali = rs.getString(7);
                String Denda = rs.getString(8);
                String Status = rs.getString(9);
                String data[] = {NoAnggota,NamaPeminjam,AlamatPeminjam,JenisBuku,JudulBuku,TanggalPinjam,TanggalKembali,Denda,Status};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(perpus.class.getName()).log(Level.SEVERE, null, ex);
        }
        data.setModel(dtm);
    }

    private void setTanggal() {
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new
        java.text.SimpleDateFormat("dd/MM/yyyy");
        labeltanggal1.setText(kal.format(skrg));
    }

    private void setJam() {
        ActionListener taskPerformer = new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
        Date dt = new Date();
        int nilai_jam = dt.getHours();
        int nilai_menit = dt.getMinutes();
        int nilai_detik = dt.getSeconds();
        if (nilai_jam <= 9) {
            nol_jam = "0";
        }
        if (nilai_menit <= 9) {
            nol_menit = "0";
        }
        if (nilai_detik <= 9) {
            nol_detik = "0";
        }
        String jam = nol_jam + Integer.toString(nilai_jam);
        String menit = nol_menit + Integer.toString(nilai_menit);
        String detik = nol_detik + Integer.toString(nilai_detik);
        labeljam.setText("Jam "+jam + ":" + menit + ":" + detik);
        }
        };
        new Timer(100, taskPerformer).start();
    }
}
